### PR TITLE
Fix: V0.90 Bug fixes and enable remote loading of SIFTS data

### PR DESCRIPTION
**Pull request by piehld**

### CODE REVIEW

**Comment by piehld** [comment]
@josemduarte FYI, this should fix the SIFTS HTTP issue. You can revert the ExDB configuration setting back to the HTTP endpoint.

**Comment by josemduarte** [comment]
Thanks @piehld . I'll revert.

**Comment by piehld** [comment]
@josemduarte FYI, this update has now been pushed to PyPI, so you may now revert all the past reverts to retrieve SIFTS data over HTTP instead of from the sandbox.

**Comment by josemduarte** [comment]
Great news, thanks! I'll revert rcsb-configs and weekly-update-workflow

**Pull request merged**
