### PR TITLE
Add Docker build and push CI/CD workflow configurations for use by GitHub Actions

### PR DESCRIPTION
**Pull request by piehld**
[RO-4305](https://rcsbpdb.atlassian.net/browse/RO-4305): We need an automated CI/CD pipeline to create docker images for ExDB pipeline. Docker images should be pushed to Harbor, our internal docker repository.

### CODE REVIEW

**Comment by henrychao-rcsb** [comment]
Hi @piehld, can you address the Dockerfile linting findings which were identified in the workflow run? For examples on how to pin versions for `apt-get` packages, you can reference https://github.com/rcsb/devops-runner-images/blob/master/gh-actions-runner-node-20/Dockerfile#L23-L48. I don't have an example handy for pinning the pip package versions in the `requirements.txt` file, but you can reference the pip documentation for the syntax: https://pip.pypa.io/en/stable/topics/repeatable-installs/

**Comment by piehld** [comment]
Thanks @henrychao-rcsb, sure I can easily address the linting issues. Before I do though, can you confirm that the other `workflow-docker.yml` file looks OK (i.e., should I be pushing to the `devops` project on Harbor)?

**Review by henrychao-rcsb — CHANGES_REQUESTED** [review]
Suggesting changes to the workflow definition.

**Review by henrychao-rcsb — APPROVED** [review]
LGTM

**Pull request merged**
